export const CATEGORIES = [
  {
    slug: 'mini-wet-wipes-lines',
    name: 'Mini Wet Wipes Lines',
    description: 'Dual-channel lines for compact individual packs and grouped multi-pack formats.',
  },
  {
    slug: 'portable-wet-wipes-lines',
    name: 'Portable Wet Wipes Lines',
    description: 'Production and packing configurations for portable multi-sheet wet wipes packs.',
  },
  {
    slug: 'multi-pack-wet-wipes-lines',
    name: 'Multi-Pack Wet Wipes Lines',
    description: 'Integrated production lines for cube packs and folded multi-sheet wet wipes formats.',
  },
  {
    slug: 'single-multi-sheet-wet-wipes-lines',
    name: 'Single and Multi-Sheet Wet Wipes Lines',
    description: 'High-speed equipment for individual sachets and one-to-three-sheet wet wipes packs.',
  },
  {
    slug: 'canister-roll-wipes-equipment',
    name: 'Canister and Roll Wipes Equipment',
    description: 'Rewinding and perforating equipment for barrel and canister wet wipes rolls.',
  },
]

const commonApplications = ['Personal care wet wipes', 'Household wet wipes', 'Hospitality and travel wet wipes']

export const PRODUCTS = [
  {
    key: 'lzc-wftg60b-cube-pack-line',
    slug: 'lzc-wftg60b-cube-pack-line',
    model: 'LZC-WFTG60B',
    name: 'Cube Pack Baby Wipes Production Line',
    shortName: 'Cube Pack Baby Wipes Line',
    categorySlug: 'multi-pack-wet-wipes-lines',
    categoryName: 'Multi-Pack Wet Wipes Lines',
    summary: 'A coordinated line for folded cube-pack baby wipes, covering web handling, liquid application, cutting, stacking, and downstream packing interfaces.',
    overview: 'The customer brochure identifies LZC-WFTG60B as a cube pack baby wipes production line. Its line layout combines multiple folding stations with liquid application, cutting, stacking, and packing sections for a continuous workshop flow.',
    features: ['Multi-station web feeding and folding', 'Liquid application and flow control', 'Cutting and independent stack counting', 'Interfaces for downstream packing equipment'],
    processSteps: ['Material feeding', 'Liquid application', 'Folding and cutting', 'Counting and stacking', 'Packing hand-off'],
    applications: ['Cube-pack baby wipes', 'Folded multi-sheet wet wipes', 'Soft-pack wet wipes'],
    specifications: { Model: 'LZC-WFTG60B', 'Line format': 'Cube pack baby wipes production line', 'Source document': 'LWFTG60B technical sheet' },
  },
  {
    key: 'lzc-lpdt20-super-mini-line',
    slug: 'lzc-lpdt20-super-mini-line',
    model: 'LZC-LPDT20',
    name: 'Dual-Channel Super Mini Wet Wipes Production Line',
    shortName: 'Dual-Channel Super Mini Line',
    categorySlug: 'mini-wet-wipes-lines',
    categoryName: 'Mini Wet Wipes Lines',
    summary: 'A dual-channel super mini wet wipes machine connected to a simple 4/6/8/10-in-one grouped-pack configuration.',
    overview: 'LZC-LPDT20 is documented as a dual-channel super mini wet wipes machine with a simple grouped-pack line. The configuration brings web feeding, folding, liquid application, cutting, and pack grouping into one compact production path.',
    features: ['Dual-channel folding section', 'Automatic material splicing and tension control', 'Synchronized cutting and stack handling', 'Simple 4/6/8/10-in-one grouped-pack configuration'],
    processSteps: ['Dual-roll feeding', 'Folding and wetting', 'Cutting', 'Primary packing', 'Grouped packing'],
    applications: ['Super mini wet wipes sachets', 'Four-pack bundles', 'Six-, eight-, and ten-pack bundles'],
    specifications: { Model: 'LZC-LPDT20', 'Line format': 'Dual-channel super mini line with simple grouped packing', 'Source document': 'LPDT20 technical sheet' },
  },
  {
    key: 'lzc-lpdt60-super-mini-line',
    slug: 'lzc-lpdt60-super-mini-line',
    model: 'LZC-LPDT60',
    name: 'Dual-Channel Super Mini Wet Wipes Robotic Packing Line',
    shortName: 'Super Mini Robotic Packing Line',
    categorySlug: 'mini-wet-wipes-lines',
    categoryName: 'Mini Wet Wipes Lines',
    summary: 'A dual-channel super mini wet wipes line paired with robotic handling and 4/6/8/10-in-one grouped packing.',
    overview: 'LZC-LPDT60 extends the dual-channel super mini wet wipes process with robotic handling and a grouped packing section. Its documented arrangement is intended to connect primary pack output with multi-pack collation.',
    features: ['Dual-channel folding and primary packing', 'Automatic material splicing and tension control', 'Robotic handling between line sections', '4/6/8/10-in-one grouped-pack configuration'],
    processSteps: ['Dual-roll feeding', 'Folding and wetting', 'Primary packing', 'Robotic transfer', 'Grouped packing'],
    applications: ['Super mini wet wipes sachets', 'Retail multi-packs', 'Travel wet wipes bundles'],
    specifications: { Model: 'LZC-LPDT60', 'Line format': 'Dual-channel super mini line with robotic grouped packing', 'Source document': 'LPDT60 technical sheet' },
    certificate: 'CE certificate M.2025.206.C117237 applies to model LZC-LPDT60.',
  },
  {
    key: 'lzc-lpm100-portable-wipes-line',
    slug: 'lzc-lpm100-portable-wipes-line',
    model: 'LZC-LPM100',
    name: 'Portable Wet Wipes Production Line',
    shortName: 'Portable Wet Wipes Line',
    categorySlug: 'portable-wet-wipes-lines',
    categoryName: 'Portable Wet Wipes Lines',
    summary: 'A production-line configuration for compact portable wet wipes packs, including ten-sheet and twenty-sheet output examples supplied by the customer.',
    overview: 'LZC-LPM100 is the customer-designated portable wet wipes line. The supplied product examples show compact ten-sheet and twenty-sheet pack formats, while the final line interfaces are confirmed for each project.',
    features: ['Portable multi-sheet pack focus', 'Compact production-line arrangement', 'Configurable folding and packing interfaces', 'Output format confirmed per project'],
    processSteps: ['Material feeding', 'Folding and wetting', 'Counting', 'Pack forming and sealing', 'Finished-pack discharge'],
    applications: ['Ten-sheet portable wet wipes', 'Twenty-sheet portable wet wipes', 'Compact travel packs'],
    specifications: { Model: 'LZC-LPM100', 'Line format': 'Portable wet wipes production line', 'Source document': 'LPM100 equipment drawing' },
  },
  {
    key: 'lzc-lpms20-portable-ten-pack-line',
    slug: 'lzc-lpms20-portable-ten-pack-line',
    model: 'LZC-LPMS20',
    name: 'Double-Row Portable Wet Wipes and Ten-Pack Line',
    shortName: 'Double-Row Portable Ten-Pack Line',
    categorySlug: 'portable-wet-wipes-lines',
    categoryName: 'Portable Wet Wipes Lines',
    summary: 'A double-row portable wet wipes line documented with a two-in-one production layout and a ten consecutive pack machine.',
    overview: 'LZC-LPMS20 combines a double-row portable wet wipes production path with a downstream ten consecutive pack machine. The customer technical sheet presents the complete arrangement as one coordinated line.',
    features: ['Double-row material handling', 'Two-in-one production arrangement', 'Primary pack discharge and transfer', 'Ten consecutive pack section'],
    processSteps: ['Double-row feeding', 'Folding and wetting', 'Primary packing', 'Pack transfer', 'Ten-pack collation'],
    applications: ['Portable wet wipes packs', 'Ten-pack retail bundles', 'Grouped travel packs'],
    specifications: { Model: 'LZC-LPMS20', 'Line format': 'Double-row portable two-in-one line with ten consecutive packing', 'Source document': 'LPMS20 technical sheet' },
  },
  {
    key: 'lzc-lpt60-cubic-pack-line',
    slug: 'lzc-lpt60-cubic-pack-line',
    model: 'LZC-LPT60',
    name: 'Double-Row Cubic Pack Wet Wipes Production Line',
    shortName: 'Double-Row Cubic Pack Line',
    categorySlug: 'multi-pack-wet-wipes-lines',
    categoryName: 'Multi-Pack Wet Wipes Lines',
    summary: 'A double-row folded two-in-one wet wipes production line for cubic multi-sheet packs.',
    overview: 'LZC-LPT60 is documented as a double-row folded wet wipes line for cubic pack formats. Its equipment arrangement connects twin material paths with folding, wetting, cutting, and pack forming sections.',
    features: ['Double-row material feeding', 'Folded two-in-one production format', 'Coordinated liquid application and cutting', 'Cubic pack forming and sealing'],
    processSteps: ['Double-row feeding', 'Folding and wetting', 'Cutting and counting', 'Cubic pack forming', 'Finished-pack discharge'],
    applications: ['Cubic wet wipes packs', 'Folded multi-sheet wipes', 'Household and personal care packs'],
    specifications: { Model: 'LZC-LPT60', 'Line format': 'Double-row folded two-in-one cubic pack line', 'Source document': 'LPG60 technical sheet' },
  },
  {
    key: 'lzc-scm400tg-single-wipe-line',
    slug: 'lzc-scm400tg-single-wipe-line',
    model: 'LZC-SCM400TG',
    name: 'High-Speed Single Wet Wipes Production and Secondary Packing Line',
    shortName: 'Single Wipe and Secondary Packing Line',
    categorySlug: 'single-multi-sheet-wet-wipes-lines',
    categoryName: 'Single and Multi-Sheet Wet Wipes Lines',
    summary: 'A high-speed single wet wipes machine connected to a secondary packaging section for grouped finished packs.',
    overview: 'LZC-SCM400TG is shown as a single-wipe production line with a connected secondary packaging machine. The documented line covers roll handling, folding, liquid application, cutting, primary packing, and grouped-pack handling.',
    features: ['Multi-shaft material feeding', 'Automatic splicing and tension control', 'Single-wipe primary packing', 'Connected secondary packaging section'],
    processSteps: ['Material feeding', 'Folding and wetting', 'Cutting', 'Primary sachet packing', 'Secondary packing'],
    applications: ['Single wet wipes sachets', 'Hospitality wipes', 'Grouped single-wipe packs'],
    specifications: { Model: 'LZC-SCM400TG', 'Line format': 'Single wet wipes machine with secondary packing', 'Source document': 'LSCM400TG technical sheet' },
  },
  {
    key: 'lzc-tr150-barrel-wipes-rewinder',
    slug: 'lzc-tr150-barrel-wipes-rewinder',
    model: 'LZC-TR150',
    name: 'Barrel Wet Wipes Rewinder',
    shortName: 'Barrel Wet Wipes Rewinder',
    categorySlug: 'canister-roll-wipes-equipment',
    categoryName: 'Canister and Roll Wipes Equipment',
    summary: 'A rewinding and perforating machine for continuous wet wipes rolls used in barrel and canister formats.',
    overview: 'LZC-TR150 is the customer-designated barrel wet wipes rewinder. The supplied sheet shows a material unwind, slitting and perforating section, rewinding station, and controls for producing tear-off rolls.',
    features: ['Large-roll material unwind', 'Slitting and point-breaking perforation', 'Servo-controlled rewinding', 'Touch-screen operation interface'],
    processSteps: ['Material unwind', 'Slitting', 'Perforation', 'Rewinding', 'Finished-roll discharge'],
    applications: ['Barrel wet wipes rolls', 'Canister wet wipes rolls', 'Tear-off roll wipes'],
    specifications: { Model: 'LZC-TR150', 'Line format': 'Barrel wet wipes rewinder', 'Source document': 'TR150 technical sheet' },
  },
  {
    key: 'lzc-scm400-single-wipe-line',
    slug: 'lzc-scm400-single-wipe-line',
    model: 'LZC-SCM400',
    name: 'High-Speed Single Wet Wipes Production Line',
    shortName: 'High-Speed Single Wipe Line',
    categorySlug: 'single-multi-sheet-wet-wipes-lines',
    categoryName: 'Single and Multi-Sheet Wet Wipes Lines',
    summary: 'A high-speed line for folding, wetting, cutting, and packing individual wet wipes sachets.',
    overview: 'LZC-SCM400 is the customer-designated high-speed single wet wipes line. Its documented process brings material control, folding, wetting, cutting, and primary sachet packing into one production arrangement.',
    features: ['Multi-shaft roll handling', 'Folding and liquid application', 'Synchronized cutting', 'Single-sachet primary packing'],
    processSteps: ['Material feeding', 'Folding and wetting', 'Cutting', 'Sachet forming and sealing', 'Finished-pack discharge'],
    applications: commonApplications,
    specifications: { Model: 'LZC-SCM400', 'Line format': 'High-speed single wet wipes production line', 'Source document': 'SCM400 technical sheet' },
  },
  {
    key: 'lzc-scm400dt-multi-sheet-line',
    slug: 'lzc-scm400dt-multi-sheet-line',
    model: 'LZC-SCM400DT',
    name: 'High-Speed One-to-Three-Sheet Wet Wipes Line',
    shortName: 'One-to-Three-Sheet Wipes Line',
    categorySlug: 'single-multi-sheet-wet-wipes-lines',
    categoryName: 'Single and Multi-Sheet Wet Wipes Lines',
    summary: 'A high-speed line for single-, double-, or triple-sheet wet wipes packs with a connected secondary packing section.',
    overview: 'LZC-SCM400DT is documented for one-, two-, and three-sheet wet wipes formats. The line combines roll handling, folding, liquid application, cutting, primary pack forming, and secondary pack transfer.',
    features: ['One-to-three-sheet format range', 'Multi-shaft feeding and tension control', 'Primary pack forming and sealing', 'Connected secondary packing section'],
    processSteps: ['Material feeding', 'Folding and wetting', 'Sheet counting and cutting', 'Primary packing', 'Secondary packing'],
    applications: ['Single-sheet wet wipes', 'Double-sheet wet wipes', 'Triple-sheet wet wipes'],
    specifications: { Model: 'LZC-SCM400DT', 'Line format': 'High-speed one-to-three-sheet line with secondary packing', 'Source document': 'SCM400DT technical sheet' },
  },
]
